//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odevler
    {
        public int Odevid { get; set; }
        public string DersAdi { get; set; }
        public string OdevBaslik { get; set; }
        public string OdevKonusu { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
    }
}
